name: Laravel Auto Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: |
            cd /var/www/html/quran
            git pull origin main
            php artisan optimize:clear
            php artisan cache:clear
